######################################################################
# Automatically generated by qmake (3.0) Sat Nov 26 11:32:03 2016
######################################################################

TEMPLATE = app
TARGET = glew_glfw
INCLUDEPATH += .
LIBS += -lGL -lGLEW -lglfw

# Input
HEADERS += LoadObj.hpp shader.hpp
SOURCES += main.cpp

DISTFILES += \
    shader/teapot.frag \
    shader/teapot.vert
